name: baby_step_up_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http:
  freezed_annotation:
  hooks_riverpod: '>=1.0.0-0'
  simple_logger:
  shared_preferences: ^2.0.6
  swipebuttonflutter: ^1.0.0

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  image_test_utils:
    git:
      url: https://github.com/mono0926/image_test_utils.git
      ref: add-compressionState
  json_serializable:
  mockito:
  pedantic_mono:

flutter:
  uses-material-design: true

environment:
  sdk: '>=2.13.0'
  flutter: '>=2.0.0'

